#!/usr/bin/env python3
"""
Generates backend/src/main/resources/db/seed/posts_import.sql from posts.json.

WHAT THIS CAN AND CANNOT DO
---------------------------
SQL cannot put objects into MinIO. TARGET: `blog` / `blog_text` / `blog_gallery` — NOT `event`. These are write-ups of things that
already happened, which is what the site renders as a post (post.jsx / blog-index.jsx). `event`
is for registerable events and carries starts_at, capacity and registration columns that do not
apply. The activity date is written to publish_at / published_at, so the archive is chronological.

This file seeds the blog rows ONLY, and must be
run AFTER the 241 images exist in the media table — i.e. after `load.py --media-only`, or after
any other upload that produced media rows. It resolves every image by `media.file_name`, never
by a hard-coded id, because ids differ between dev and prod while the Facebook file names are
stable. That is what makes one file loadable into both environments.

It goes in db/seed/, NOT db/migration/, matching home_blocks.sql and the rule stated in
application.yml: migrations carry schema and closed-list reference data only; content arrives
by dump/restore. Putting 73 events in db/migration would also mean Flyway checksums an
editorial file — edit one typo afterwards and every environment fails to start.

Idempotent: every insert is guarded on the slug not already existing, so running it twice adds
nothing and touches nothing already edited in the CMS.

  python3 make_seed.py --events posts.json \
      --out ../../backend/src/main/resources/db/seed/events_import.sql
"""
import argparse, json
from pathlib import Path

# blog_text has no venue columns and post.jsx renders no venue, so tcVenue stays in posts.json
# as source information and is deliberately not written here.
TEXT_FIELDS = [
    ("tc_title", "tcTitle"), ("en_title", "enTitle"), ("sc_title", "scTitle"),
    ("tc_summary", "tcSummary"), ("en_summary", "enSummary"), ("sc_summary", "scSummary"),
    ("tc_body", "tcBody"), ("en_body", "enBody"), ("sc_body", "scBody"),
]


def service_id(code):
    """Resolve by the stable `code` from V2 reference data — ids differ per environment."""
    if not code:
        return "NULL"
    return f"(SELECT id FROM service WHERE code = {q(code)} LIMIT 1)"


def q(v):
    """Quote a SQL string literal, or NULL."""
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def media_id(name):
    """Resolve an image to its media row by file name — ids differ per environment."""
    if not name:
        return "NULL"
    base = name.split("/")[-1]
    return f"(SELECT id FROM media WHERE file_name = {q(base)} ORDER BY id LIMIT 1)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", default="posts.json")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    events = json.loads(Path(args.events).read_text(encoding="utf-8"))
    L = []

    L.append("""-- LucaBridge — 73 legacy Facebook write-ups as BLOG POSTS.
-- Generated by tools/content-import/make_seed.py.
-- DO NOT EDIT BY HAND: regenerate instead, or your change is lost on the next run.
--
-- NOT a Flyway migration, and deliberately so — same rule as home_blocks.sql. Migrations here
-- carry schema and closed-list reference data only; this is editorial content. It is also far
-- too likely to need a typo fix, and a checksummed migration that changed would stop every
-- environment from starting. Nothing runs this for you, in any environment.
--
-- PREREQUISITE: the images must already be in the media table. SQL cannot upload to MinIO.
-- Run `python3 load.py --media-only` first (dev and prod each), then this file. Every image is
-- resolved by media.file_name and every service by service.code, never by id, so the same file
-- loads into any environment even though the ids differ between them.
--
-- Target is blog / blog_text / blog_gallery, NOT event. These are retrospective write-ups — what
-- the site renders as posts — and the activity date is carried by publish_at.
--
-- Copy the file in and run it there. Works the same on macOS, Linux and Windows and — unlike
-- piping — cannot re-encode the file on the way in, which matters because almost every string
-- here is Chinese:
--
--   docker compose cp backend/src/main/resources/db/seed/posts_import.sql postgres:/tmp/posts.sql
--   docker compose exec postgres psql -U lucabridge -d lucabridge -f /tmp/posts.sql
--
-- Avoid `psql ... < file` in PowerShell: `<` is a reserved operator there, and `Get-Content |
-- psql` re-encodes the text (PowerShell 5.1 pipes to native commands as ASCII by default),
-- which turns the Chinese into question marks.
--
-- Safe to run twice: every insert is guarded on the slug not already existing, so it will not
-- duplicate posts or touch anything you have since edited in the CMS.

\\set ON_ERROR_STOP on
BEGIN;

-- Fail fast rather than silently seeding 73 posts with no images at all.
DO $$
DECLARE n bigint;
BEGIN
    SELECT count(*) INTO n FROM media;
    IF n = 0 THEN
        RAISE EXCEPTION 'media table is empty — upload the images first (python3 load.py --media-only), then re-run this file';
    END IF;
END $$;
""")

    for e in events:
        tc_body = e.get("tcBody") or ""
        if e.get("tcAppendix"):
            # the tc editor's note is joined on here, exactly as load.py does it
            tc_body = (tc_body + "\n\n" + e["tcAppendix"]).strip()
        vals = dict(e)
        vals["tcBody"] = tc_body

        gallery = [g.split("/")[-1] for g in e["galleryImages"]]
        if e.get("coverFrom") == "VIDEO_POSTER" and e.get("coverImage"):
            gallery = [e["coverImage"]] + [g for g in gallery if g != e["coverImage"]]

        cols = ", ".join(c for c, _ in TEXT_FIELDS)
        sel = ",\n           ".join(q(vals.get(j)) for _, j in TEXT_FIELDS)

        L.append(f"""
-- {e['slug']}  ({(e.get('publishAt') or e.get('startsAt') or '')[:10]})  {e['status']}  [{e.get('serviceCode') or 'untagged'}]  {(e['tcTitle'] or '')[:40]}
WITH ins AS (
    INSERT INTO blog (slug, service_id, cover_media_id, author_id, read_minutes,
                      gallery_layout, status, publish_at, published_at,
                      created_by, updated_by, created_at, updated_at)
    SELECT {q(e['slug'])},
           {service_id(e.get('serviceCode'))},
           {media_id(e.get('coverImage'))},
           NULL,
           {e.get('readMinutes') or 'NULL'},
           {q(e['galleryLayout'])},
           {q(e['status'])},
           {q(e.get('publishAt'))}::timestamptz,
           {q(e.get('publishAt'))}::timestamptz,
           (SELECT id FROM app_user ORDER BY id LIMIT 1),
           (SELECT id FROM app_user ORDER BY id LIMIT 1),
           now(), now()
    WHERE NOT EXISTS (SELECT 1 FROM blog WHERE slug = {q(e['slug'])})
    RETURNING id
)
INSERT INTO blog_text (blog_id, {cols})
SELECT id,
           {sel}
FROM ins;""")

        if gallery:
            rows = ",\n        ".join(f"({q(n)}, {i})" for i, n in enumerate(gallery))
            L.append(f"""
INSERT INTO blog_gallery (blog_id, media_id, sort_order)
SELECT b.id, m.id, v.ord
FROM blog b
CROSS JOIN (VALUES
        {rows}
    ) AS v(fn, ord)
JOIN media m ON m.file_name = v.fn
WHERE b.slug = {q(e['slug'])}
ON CONFLICT (blog_id, media_id) DO NOTHING;""")

    L.append("""

-- Report anything that did not land, rather than leaving it to be found on the live site.
DO $$
DECLARE missing_cover int; total int; untagged int;
BEGIN
    SELECT count(*) INTO total FROM blog WHERE deleted_at IS NULL;
    SELECT count(*) INTO missing_cover FROM blog WHERE cover_media_id IS NULL AND deleted_at IS NULL;
    SELECT count(*) INTO untagged FROM blog WHERE service_id IS NULL AND deleted_at IS NULL;
    RAISE NOTICE 'posts in table: %, without a cover image: %, without a service tag: %',
                 total, missing_cover, untagged;
    IF missing_cover > 0 THEN
        RAISE NOTICE 'a missing cover usually means the images were not uploaded before this file was run';
    END IF;
END $$;

COMMIT;
""")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8")
    imgs = sum(len(e["galleryImages"]) for e in events)
    print(f"wrote {out}")
    print(f"  {len(events)} blog posts, {imgs} gallery rows, {out.stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    main()
