-- Phase A ACL: DB-backed CMS accounts and their roles.
--
-- Runs in PROD only (dev has spring.flyway.enabled=false and lets Hibernate
-- create-drop build the schema instead). IF NOT EXISTS keeps it a safe no-op on
-- a prod DB where these tables were already created by ddl-auto=update.
--
-- Column types mirror the JPA mappings in entity/AppUser.java so Hibernate
-- schema validation passes: IDENTITY id, unique username, bcrypt hash, and a
-- user_role element-collection table (one row per role).

CREATE TABLE IF NOT EXISTS app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(120),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS user_role (
    user_id BIGINT      NOT NULL,
    role    VARCHAR(20) NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
        REFERENCES app_user (id) ON DELETE CASCADE
);
