-- Phase A media library: catalogue of uploaded images (standalone, not post-scoped).
-- Prod-only (dev uses Hibernate create-drop). IF NOT EXISTS keeps it a safe no-op.
CREATE TABLE IF NOT EXISTS media_asset (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key   VARCHAR(400) NOT NULL,
    url          VARCHAR(700) NOT NULL,
    filename     VARCHAR(300),
    content_type VARCHAR(100),
    size_bytes   BIGINT,
    alt_text     VARCHAR(500),
    created_at   TIMESTAMP,
    CONSTRAINT uk_media_asset_object_key UNIQUE (object_key)
);
